site_name: Learn With Shin


theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'light blue'

nav:
  - Home: index.md
  - Files: files.md
  - Practices: 
    - 'Top Rated Movies': "./practices/top_rated_movies.md"